micronaut:
  application:
    name: mnStockBroker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
      authentication: bearer
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:changeThisSecretToALongerSecureString}"'
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'com.bartbruneel.entities'
    properties:
      hibernate:
        show_sql: false
hello:
  world:
    message: Hello from application.yml
    translation:
      de: "Hallo Welt"
      en: "Hello World"
